FROM node:20.18.1-alpine AS development

RUN apk add --no-cache libc6-compat python3 make g++ curl

WORKDIR /app

# Copiar arquivos de dependências
COPY package.json package-lock.json* ./

# Instalar dependências
ENV NODE_OPTIONS="--max-old-space-size=768"
RUN npm ci

# Copiar código fonte
COPY . .

# Gerar Prisma Client
RUN npx prisma generate

EXPOSE 3000

# Comando para desenvolvimento
CMD ["npx", "next", "dev"]
